FROM node:23

ARG NODE_ENV
ARG NEXT_PUBLIC_WEB_VERSION
ARG DANGEROUSLY_DISABLE_HOST_CHECK
ARG NEXT_PUBLIC_BASE_PATH

# RUN apk add --update git openssh-client

WORKDIR /var/www/app

COPY . ./

RUN rm -rf /var/www/app/.env.local

RUN rm -rf /var/www/app/package-lock.json

# RUN npm i -g npm@10.9.2

RUN npm install

RUN NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH NODE_ENV=$NODE_ENV NEXT_PUBLIC_WEB_VERSION=$NEXT_PUBLIC_WEB_VERSION DANGEROUSLY_DISABLE_HOST_CHECK=$DANGEROUSLY_DISABLE_HOST_CHECK npm run build

CMD NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH NODE_ENV=$NODE_ENV NEXT_PUBLIC_WEB_VERSION=$NEXT_PUBLIC_WEB_VERSION DANGEROUSLY_DISABLE_HOST_CHECK=$DANGEROUSLY_DISABLE_HOST_CHECK npm run start

EXPOSE 3000
